//! Safe Rust wrapper around libsoxr for streaming audio resampling.
//!
//! Uses sinc interpolation with internal filter state for seamless chunk
//! processing — no clicks or discontinuities at boundaries.
//!
//! # Example
//! ```ignore
//! use soxr::SoxrStreamResampler;
//!
//! let mut resampler = SoxrStreamResampler::new(48000, 16000).unwrap();
//! let resampled = resampler.process(&pcm16_le_bytes);
//! ```

// ── Raw FFI bindings (generated by bindgen from soxr.h) ────────
#[allow(non_upper_case_globals)]
#[allow(non_camel_case_types)]
#[allow(dead_code)]
mod ffi;

use std::ffi::{c_void, CStr};
use std::ptr;

// ── Public API ─────────────────────────────────────────────────

/// Stateful streaming resampler backed by libsoxr.
///
/// Create once per stream, then call [`process()`](SoxrStreamResampler::process)
/// for each audio chunk. Internal state ensures seamless output across
/// chunk boundaries.
pub struct SoxrStreamResampler {
    soxr: ffi::soxr_t,
    src_rate: u32,
    dst_rate: u32,
    /// Pre-allocated output buffer (avoids per-call allocation).
    out_buf: Vec<i16>,
}

// soxr_t is safe to send across threads (single-writer).
unsafe impl Send for SoxrStreamResampler {}

impl SoxrStreamResampler {
    /// Create a new streaming resampler.
    ///
    /// Uses 16-bit HQ — matches PCM16 input precision with a good
    /// anti-aliasing filter. Negligible CPU cost for voice workloads.
    pub fn new(src_rate: u32, dst_rate: u32) -> Result<Self, String> {
        let io_spec = unsafe {
            ffi::soxr_io_spec(
                ffi::soxr_datatype_t_SOXR_INT16_I,
                ffi::soxr_datatype_t_SOXR_INT16_I,
            )
        };

        let quality_spec =
            unsafe { ffi::soxr_quality_spec(ffi::SOXR_16_BITQ as std::os::raw::c_ulong, 0) };

        let mut error: ffi::soxr_error_t = ptr::null();

        let soxr = unsafe {
            ffi::soxr_create(
                src_rate as f64,
                dst_rate as f64,
                1, // mono
                &mut error,
                &io_spec,
                &quality_spec,
                ptr::null(),
            )
        };

        if !error.is_null() {
            let msg = unsafe { CStr::from_ptr(error) };
            return Err(format!("soxr_create: {}", msg.to_string_lossy()));
        }
        if soxr.is_null() {
            return Err("soxr_create returned null".into());
        }

        // Pre-allocate for up to 100ms of input at the higher rate
        let max_in = (src_rate.max(dst_rate) as usize * 100) / 1000;
        let max_out = (max_in as f64 * dst_rate as f64 / src_rate as f64) as usize + 64;

        Ok(Self {
            soxr,
            src_rate,
            dst_rate,
            out_buf: vec![0i16; max_out],
        })
    }

    /// Resample a chunk of **PCM16 LE mono** audio.
    ///
    /// Returns resampled PCM16 LE bytes.  Internal filter state is
    /// carried across calls — output is seamless.
    pub fn process(&mut self, audio: &[u8]) -> Vec<u8> {
        const SAMPLE_WIDTH: usize = 2;

        if self.src_rate == self.dst_rate {
            return audio.to_vec();
        }

        let n_samples = audio.len() / SAMPLE_WIDTH;
        if n_samples == 0 {
            return Vec::new();
        }

        // Decode PCM16 LE
        let input: Vec<i16> = (0..n_samples)
            .map(|i| i16::from_le_bytes([audio[i * 2], audio[i * 2 + 1]]))
            .collect();

        // Grow output buffer if needed
        let need = (n_samples as f64 * self.dst_rate as f64 / self.src_rate as f64) as usize + 64;
        if self.out_buf.len() < need {
            self.out_buf.resize(need, 0);
        }

        let mut odone: usize = 0;

        let err = unsafe {
            ffi::soxr_process(
                self.soxr,
                input.as_ptr() as *const c_void,
                n_samples,
                ptr::null_mut(),
                self.out_buf.as_mut_ptr() as *mut c_void,
                self.out_buf.len(),
                &mut odone,
            )
        };

        if !err.is_null() {
            return Vec::new();
        }

        // Encode back to PCM16 LE bytes
        let mut result = Vec::with_capacity(odone * SAMPLE_WIDTH);
        for &s in &self.out_buf[..odone] {
            result.extend_from_slice(&s.to_le_bytes());
        }
        result
    }
}

impl Drop for SoxrStreamResampler {
    fn drop(&mut self) {
        unsafe {
            ffi::soxr_delete(self.soxr);
        }
    }
}
