"""add model_messages_json to builder_conversations

Revision ID: e8b1e2a0664f
Revises: 23bcafb9f857
Create Date: 2026-03-08 14:19:13.928212
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8b1e2a0664f'
down_revision: str | None = '23bcafb9f857'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('builder_conversations', sa.Column('model_messages_json', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('builder_conversations', 'model_messages_json')
    # ### end Alembic commands ###
