"""add_oauth_apps_table

Revision ID: f61f165b24ec
Revises: c4e5f6a7b8d9
Create Date: 2026-03-11 14:59:27.122251
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f61f165b24ec'
down_revision: str | None = 'c4e5f6a7b8d9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_apps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('integration_name', sa.String(length=100), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('client_secret_iv', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_apps_integration_name'), 'oauth_apps', ['integration_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_apps_integration_name'), table_name='oauth_apps')
    op.drop_table('oauth_apps')
    # ### end Alembic commands ###
