# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stt.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tstt.proto\x12\x03stt\"~\n\nSttRequest\x12\x1f\n\x05\x61udio\x18\x01 \x01(\x0b\x32\x0e.stt.AudioDataH\x00\x12!\n\x08\x66inalize\x18\x02 \x01(\x0b\x32\r.stt.FinalizeH\x00\x12!\n\x05\x63lose\x18\x03 \x01(\x0b\x32\x10.stt.CloseStreamH\x00\x42\t\n\x07request\"\x1d\n\tAudioData\x12\x10\n\x08pcm_data\x18\x01 \x01(\x0c\"\n\n\x08\x46inalize\"\r\n\x0b\x43loseStream\"F\n\x0bSttResponse\x12+\n\ntranscript\x18\x01 \x01(\x0b\x32\x15.stt.TranscriptResultH\x00\x42\n\n\x08response\"l\n\x10TranscriptResult\x12\x10\n\x08is_final\x18\x01 \x01(\x08\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x12\n\nstart_time\x18\x04 \x01(\x02\x12\x10\n\x08\x64uration\x18\x05 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stt_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STTREQUEST']._serialized_start=18
  _globals['_STTREQUEST']._serialized_end=144
  _globals['_AUDIODATA']._serialized_start=146
  _globals['_AUDIODATA']._serialized_end=175
  _globals['_FINALIZE']._serialized_start=177
  _globals['_FINALIZE']._serialized_end=187
  _globals['_CLOSESTREAM']._serialized_start=189
  _globals['_CLOSESTREAM']._serialized_end=202
  _globals['_STTRESPONSE']._serialized_start=204
  _globals['_STTRESPONSE']._serialized_end=274
  _globals['_TRANSCRIPTRESULT']._serialized_start=276
  _globals['_TRANSCRIPTRESULT']._serialized_end=384
# @@protoc_insertion_point(module_scope)
