// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v4.25.0
// source: agent.proto

export const protobufPackage = "agent";

export enum AudioLayout {
  AUDIO_LAYOUT_UNSPECIFIED = 0,
  AUDIO_LAYOUT_STEREO = 1,
  AUDIO_LAYOUT_MONO = 2,
  UNRECOGNIZED = -1,
}

export enum AudioFormat {
  AUDIO_FORMAT_UNSPECIFIED = 0,
  AUDIO_FORMAT_OPUS = 1,
  AUDIO_FORMAT_WAV = 2,
  UNRECOGNIZED = -1,
}

/** Session recording configuration */
export interface RecordingConfig {
  enabled: boolean;
  output_uri: string;
  audio_layout: AudioLayout;
  sample_rate: number;
  audio_format: AudioFormat;
  max_duration_secs: number;
  save_transcript: boolean;
  include_tool_details: boolean;
  include_llm_metadata: boolean;
}

/** Tool parameter definition */
export interface ParamDef {
  name: string;
  /** e.g., "string", "integer", "boolean" */
  type: string;
  description: string;
  required: boolean;
  /** Valid values for enum types */
  options: string[];
}

/** A tool definition (always a JS script) */
export interface ToolDef {
  description: string;
  script: string;
  params: ParamDef[];
  /** If true (default), barge-in drops the tool result */
  cancel_on_barge_in: boolean;
  /** If true, this tool has side effects */
  side_effect: boolean;
}

/** A single node in the graph */
export interface NodeDef {
  system_prompt: string;
  /** keys referencing AgentGraphDef.tools */
  tools: string[];
  /** node IDs this node can transfer to */
  edges: string[];
  model?: string | undefined;
  temperature?: number | undefined;
  max_tokens?: number | undefined;
  /** TTS voice override */
  voice_id?: string | undefined;
  greeting?: string | undefined;
}

/** A complete agent graph */
export interface AgentGraphDef {
  /** The ID of the node to start with */
  entry: string;
  /** All nodes keyed by ID */
  nodes: { [key: string]: NodeDef };
  /** All tool definitions keyed by tool name */
  tools: { [key: string]: ToolDef };
  /** -- Agent-wide settings -- */
  language?: string | undefined;
  /** IANA timezone */
  timezone?: string | undefined;
  /** Default TTS voice ID */
  voice_id?: string | undefined;
  /** e.g. "elevenlabs" */
  tts_provider?: string | undefined;
  /** e.g. "eleven_turbo_v2" */
  tts_model?: string | undefined;
  /** Session recording configuration */
  recording?: RecordingConfig | undefined;
  /** Envelope field for versions (e.g. "v3_graph") */
  config_schema_version?: string | undefined;
  gemini_live_api_key?: string | undefined;
  gemini_live_model?: string | undefined;
}

export interface AgentGraphDef_NodesEntry {
  key: string;
  value: NodeDef | undefined;
}

export interface AgentGraphDef_ToolsEntry {
  key: string;
  value: ToolDef | undefined;
}
